name: marchic
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  dio: ^5.4.1
  fluentui_system_icons: ^1.1.236
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  freezed: ^2.4.7
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.5
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/logos/
    - assets/
    - assets/Logos/Free shipping-rafiki 1.svg
  uses-material-design: true
